### ISSUE TITLE
Accepting PRs? 

### ISSUE THREAD

**Issue by andrewhowdencom** [clockworksoul/helm-elasticsearch#1]
Just to bring it in line with the helm best practices stuff. I dunno when I'd have time for this, but if I do, this will be the canonical helm chart for me.

**Comment by clockworksoul** [comment]
Absolutely yes. I recognize that a few changes need to be made to the chart in the short term, and I already have a couple specific ones planned for tonight or tomorrow. Every bit of help is appreciated though!
