### ISSUE TITLE
Master nodes need statefulset support

### ISSUE THREAD

**Issue by dcwangmit01** [clockworksoul/helm-elasticsearch#15]
The latest changes for statefulset support only add it for Elasticsearch *data* nodes.  However, Elasticsearch cluster state is stored across all of nodes, especially the *master* nodes.  In order to do stateful elasticsearch well, we need the same changes to the master node templates.

Please refer to this link for information:
https://discuss.elastic.co/t/where-cluster-metadata-is-stored/44540

**Comment by clockworksoul** [comment]
Hi @dcwangmit01. 

This is a bit of a facepalm on my part. I'll take care of this this weekend. Thanks for the poke.

**Comment by sagikazarmark** [comment]
This is probably better opened and discussed in https://github.com/pires/kubernetes-elasticsearch-cluster/tree/master/stateful

**Comment by dcwangmit01** [comment]
@sagikazarmark I think both projects need it fixed, but I don't really see that project as a dependency.  This project is quite independent, if not just because of the chart templating.  I'm happy to file an issue there.

@clockworksoul Let me know if you'd like me to PR a fix.

**Comment by clockworksoul** [comment]
Hi all. Apologies for the delay on this item. I think I have my time-consuming demons slain for the time being though!

@dcwangmit01 If you already have a fix that you can drop into a PR, that would be awesome. If not I'll do it this weekend. It should only take a few minutes in either case. :)

Additionally, as soon as it's complete I'd like to request whoever submits the PR to make an equivalent one for the pires/kubernetes-elasticsearch-cluster project manifests.
