### ISSUE TITLE
Support stateful mode

### ISSUE THREAD

**Issue by calbach** [clockworksoul/helm-elasticsearch#9]
Per https://github.com/pires/kubernetes-elasticsearch-cluster/tree/master/stateful

I have a rough approximation of the changes needed: https://github.com/calbach/helm-elasticsearch

However, I don't know if it's in scope for this repo to include the stateful version and I'm not sure of the best way of supporting it:
- Separate chart
- Parameterize a single chart to work for stateful or not

**Comment by sagikazarmark** [comment]
I would love to see a stateful version of this chart.

**Comment by niclic** [comment]
I'd go with _Parameterize a single chart to work for stateful or not_, since this seems to be a common approach in many other Helm charts that I have seen.

**Comment by clockworksoul** [comment]
Hi folks. I finally got around to looking at this. As discussed, I parameterized the chart, such that "stateful mode" can be enabled by changing `.Values.data.stateful.enabled` to `true`. It is `false` by default.

Everything seems to be working nicely in AWS with `.Values.data.stateful.class` of `gp2`. If there are any issues of any kind, please let me know!

I'll leave the issue open for a couple days until I'm confident everything is working as intended.
